export const Appartments = [
  {
    id: 1,
    appartmentImg: "assets/appartments/appartment1.jpeg",
    address: "unit 302, 3243 Burligton ave, North york, Toronto",
    Price: "Price: 355,900$",
    Bedrooms: 2,
    bathrooms: 3,
  },
  {
    id: 2,
    appartmentImg: "assets/appartments/appartment2.jpeg",
    address: "unit 2302, 4332 cresent Road, North york, Toronto",
    Price: "Price: 585,700$",
    Bedrooms: 3,
    bathrooms: 2,
  },
  {
    id: 3,
    appartmentImg: "assets/appartments/appartment3.jpeg",
    address: "unit 1020, 345 Hallway street, downtown, Toronto",
    Price: "Price: 764,000$",
    Bedrooms: 3,
    bathrooms: 3,
  },
  {
    id: 4,
    appartmentImg: "assets/appartments/appartment4.jpeg",
    address: "unit: 901, 2019 Bessbrough drive, east york,Toronto",
    Price: "Price: 850,200$",
    Bedrooms: 4,
    bathrooms: 3,
  },
  {
    id: 5,
    appartmentImg: "assets/appartments/appartment5.jpeg",
    address: "unit: 405, 5434 Norway street, East york, Toronto",
    Price: "Price: 750,600$",
    Bedrooms: "2 + 1",
    bathrooms: 1,
  },
];

export const HousesData = [
  {
    id: 1,
    houseImg: "assets/houses/houseL1.jpeg",
    address: "2324 Ramsy Road , Toronto",
    Price: "Price: 850,900$",
    Bedrooms: 2,
    bathrooms: 3,
  },
  {
    id: 2,
    houseImg: "assets/houses/houseL2.jpeg",
    address: "4953 Bannf Road, Toronto",
    Price: "Price: 860,600$",
    Bedrooms: "2 + 1",
    bathrooms: 1,
  },
  {
    id: 3,
    houseImg: "assets/houses/houseL3.jpeg",
    address: "3234 Bayview ave, Toronto",
    Price: "Price: 879,000$",
    Bedrooms: 4,
    bathrooms: 3,
  },
  {
    id: 4,
    houseImg: "assets/houses/houseL4.jpeg",
    address: "456 Mount pleasent Road,Toronto",
    Price: "Price: 890,600$",
    Bedrooms: "3 + 1",
    bathrooms: 3,
  },
  {
    id: 5,
    houseImg: "assets/houses/houseL5.jpeg",
    address: "312 Millwood road,Toronto",
    Price: "Price: 850,200$",
    Bedrooms: 4,
    bathrooms: 2,
  },
  {
    id: 6,
    houseImg: "assets/houses/houseL6.jpeg",
    address: "432 pape ave , Toronto",
    Price: "Price: 950,200$",
    Bedrooms: 4,
    bathrooms: 3,
  },
  {
    id: 7,
    houseImg: "assets/houses/houseL7.jpeg",
    address: "2334 Eglinton ave East, Toronto",
    Price: "Price: 870,000$",
    Bedrooms: 2,
    bathrooms: 2,
  },
  {
    id: 8,
    houseImg: "assets/houses/houseL8.jpg",
    address: "342 Richard street, Toronto",
    Price: "Price: 1100,200$",
    Bedrooms: "4 +1",
    bathrooms: 3,
  },
  {
    id: 9,
    houseImg: "assets/houses/houseL9.jpg",
    address: "436 Danfroth ave,Toronto",
    Price: "Price: 1050,200$",
    Bedrooms: 5,
    bathrooms: 5,
  },
  {
    id: 10,
    houseImg: "assets/houses/houseL10.jpeg",
    address: "3654 Lawrence ave,Toronto",
    Price: "Price: 1255,200$",
    Bedrooms: 4,
    bathrooms: 2,
  },
];
